from typing import Optional


class Subject:
    def __init__(self, subject: str, p: Optional[int] = None) -> None: ...

    @property
    def subject(self) -> str: ...

    @subject.setter
    def subject(self, value: str) -> None: ...

    @property
    def personalization(self) -> Optional[int]: ...

    @personalization.setter
    def personalization(self, value: int) -> None: ...

    def __str__(self) -> str: ...

    def get(self) -> str: ...
