# Generated by Django 5.1.2 on 2024-11-05 01:32

import django.db.models.deletion
import posts.models
import posts.storage
from django.conf import settings
from django.db import migrations, models


def username_to_user_id(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    User = apps.get_model('accounts', 'User')

    for post in Post.objects.all():
        try:
            user = User.objects.get(username=post.username)
            post.user = user
            post.save()
        except User.DoesNotExist:
            user = User.objects.create(
                username=post.username,
                email=f"{post.username}@nonexistent.com",
                password="t3mpør4ry?"
            )
            post.user = user
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image_url_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(username_to_user_id),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=posts.storage.MediaStorage,
                upload_to=posts.models.post_image_path
            ),
        ),
    ]
